### ISSUE TITLE
Redesign the readme file

### ISSUE THREAD

**Issue by sadnyd** [sadnyd/what-type-is-my-car#1]
The Readme file is often the first file that the users read. It is a text file that contains information for the user about the software, project, code, or game, or it might contain instructions, help, or details about the patches or updates.

Try creating a good readme file that catches the eye of readers with the main points bold and clear to read.
Additionally documentation of libraries and technologies used could be added for ease of access.

**Comment by DanielZhang111** [comment]
Can I get assigned?

**Comment by sadnyd** [comment]
sure, any problems text me here or email me at sadnyd@gmail.com

**Comment by DanielZhang111** [comment]
OK I will work on this when i get home. Thanks!

**Comment by DanielZhang111** [comment]
What general information do you want about your cars?

**Comment by sadnyd** [comment]
I am making this end to end car type classification website. What it will do is, it will take an image as upload and classify it among the categories. You can check the scribble text file for the types it will classify it into, and the requirement files for the packages and libraries I am using. 
I want the readme file to look cool visually(add images, emojis, etc.)  with some documentation links attached. And most of all the readme should present my idea clearly.

**Comment by sadnyd** [comment]
If you can briefly explain the car types, that would be great too.

**Comment by DanielZhang111** [comment]
Hmmmm I will try. So in short, I take the images and classify them into the different car brands, I need to add images and emojis, and explain some differences between car types?

**Comment by sadnyd** [comment]
No, the machine learning model will do the task. Also it does not classify
the model, it classifies the cars into types like sedan , hatchback,
roadster(for reference check inside model-> dataset folder) .You only need
to modify the readme file so that anyone who reads it can get what the
project is about. In case you want to know about what is a readme file
here's a link to github :

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes

**Comment by DanielZhang111** [comment]
:O Ok I will do that instead! Thanks

**Comment by DanielZhang111** [comment]
I submitted a request.
