### ISSUE TITLE
Model fix required(mostly path based errors)

### ISSUE THREAD

**Issue by sadnyd** [sadnyd/what-type-is-my-car#4]
Check the carCropModel.ipynb

following error exists:

Cell In[80], line 19
     17 cropped_file_name = car_model +str(count) + ".png"
     18 cropped_file_path = cropped_folder + "/" + cropped_file_name
---> 19 if cv2.imwrite(cropped_file_path, cropped_image):
     20     car_model_file_names_dict[car_model].append(cropped_file_path)
     21     count += 1

error: OpenCV(4.8.1) /io/opencv/modules/imgcodecs/src/loadsave.cpp:787: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

**Comment by Apoorv012** [comment]
Hey @sadnyd I would like to work on this issue. Could you assign this to me?

**Comment by sadnyd** [comment]
Sure

**Comment by sadnyd** [comment]
Any problems text me here or at sadnyd@gmail.com

**Comment by sadnyd** [comment]
yeah i figured, checking the size for none but there was something wrong with the get_cropped_car_image function. 
Added exception handling, when exception found it just gives back a white image which is easy for me to find inside the file explorer.
Still cannot figure the underlying problem but now the code works.

Thanks for suggesting a fix, I'm closing the issue now, would have merged your code as well, but I was working on that problem myself and changed some previous code. Merging yours would create conflict at this point. 

I will be raising some other issues when countered. Thanks again

**Comment by Apoorv012** [comment]
Ok
